version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/front_react_back_node/
hooks:
  BeforeInstall:
    - location: before_install.sh
      runas: root
  AfterInstall:
    - location: after_install.sh
      runas: root
